name: Build Okular

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.10
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        # Enable source repositories to allow apt build-dep
        sed -i 's/ deb/ deb deb-src/' /etc/apt/sources.list.d/ubuntu.sources
        
        # Workaround for older/EoL releases if needed
        sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/' /etc/apt/sources.list.d/ubuntu.sources || true
        sed -i 's/security.ubuntu.com/old-releases.ubuntu.com/' /etc/apt/sources.list.d/ubuntu.sources || true
        
        apt-get update
        apt-get install --yes eatmydata
        eatmydata apt-get build-dep --yes --no-install-recommends okular
        eatmydata apt-get install --yes --no-install-recommends ninja-build cmake git

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DOKULAR_UI=both -G Ninja ..

    - name: Build
      run: |
        cd build
        ninja
