name: Build Flatpak

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  flatpak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: okular.flatpak
          manifest-path: .flatpak-manifest.json
          cache-key: flatpak-builder-${{ github.sha }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: okular-flatpak
          path: okular.flatpak
